apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc-clusip
  namespace: httpbin
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: httpbin