# Ref: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
controller:
  ingressClassResource:
    name: nginx-internal
  config:
    enable-modsecurity: true
    enable-owasp-modsecurity-crs: true
  replicaCount: 2
  service:
    annotations:
      # Refs: https://learn.microsoft.com/en-us/azure/aks/internal-lb?tabs=set-service-annotations
      #       https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#privatelinkservice-annotations
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-ilb-snet"
      # service.beta.kubernetes.io/azure-pls-create: "true"
      # service.beta.kubernetes.io/azure-pls-resource-group: "rg-use2-446692-s4-aks-afd-pls-01"
      # service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: "aks-ilb-snet"
defaultBackend:
  enabled: true