controller:
  ingressClassResource:
    name: nginx-internal
  config:
    enable-modsecurity: true
    enable-owasp-modsecurity-crs: true
  replicaCount: 3
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-pls-create: "true"
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"