controller:
  ingressClassResource:
    name: nginx-public
  config:
    enable-modsecurity: true
    enable-owasp-modsecurity-crs: true
  replicaCount: 2
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
defaultBackend:
  enabled: true